remote_theme: jeffreytse/jekyll-theme-yat #Jekyll-Theme-Yat #benc-uk/theme-msdark
title: Lear Data Modeling
buttons:
  - text: Download All
    href: https://github.com/benc-uk/icon-collection/archive/master.zip

header_pages:
  - introduction.md
  - star-schema.md
  
navigation:
  - {title: Mail, icon: envelope, url: "mailto:atanu10.yt@gmail.com"}
  - {title: Website, icon: web, url: "https://www.atanuconsulting.in/"}
  - {title: Feed, icon: rss, url: "/feed.xml"}
